### PR TITLE
Adding more growth chambers

### PR DESCRIPTION
**Pull request by waleks647**
Adds the End, Nether and Ocean growth chambers as well as their MK2 version
Moves recipes from the growth chamber to the now respective machine and adds some more recipes, namely coral and flowers.
Increased power consumption to 128 in MK2's and power buffer to 1024.
Changed speed to 3x.
Changed recipes' processing time.

### CODE REVIEW

**Comment by ProfElements** [comment]
I thought we were keeping MK2 speeds at 4x?

**Comment by waleks647** [comment]
Well making it's speed x4 would be a bit op considering it's only two GC's in the recipe, so I thought making it speed and prod X3 and power x4 would make it more balanced

**Comment by ProfElements** [comment]
That does sound right. Let me make sure these work and then will merge!

**Comment by waleks647** [comment]
Ok 👍

**Pull request merged**
