### PR TITLE
Expose Orechid recipes and clean up

### PR DESCRIPTION
**Pull request by Seggan**
Exposed the Orechid recipes, so addons/integrations can add their own. Not tested but 99.99999% sure it works

### CODE REVIEW

**Comment by ProfElements** [comment]
Did you test this? I seem to be getting errors because we are setting the block material asyncronously now. 

```
Ticker-Info:
  Type: Asynchronous

Slimefun Data:
  ID: ORECHID
  Inventory: false
  Data: {"energy-charge":"16384","id":"ORECHID"}

Stacktrace:

java.lang.IllegalStateException: Asynchronous block remove!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16)
	at net.minecraft.world.level.block.state.BlockBase.remove(BlockBase.java:145)
	at net.minecraft.world.level.block.state.BlockBase$BlockData.remove(BlockBase.java:913)
	at net.minecraft.world.level.chunk.Chunk.setType(Chunk.java:676)
	at net.minecraft.world.level.World.a(World.java:594)
	at net.minecraft.world.level.World.setTypeAndData(World.java:556)
	at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlock.setTypeAndData(CraftBlock.java:198)
	at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlock.setBlockData(CraftBlock.java:182)
	at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlock.setType(CraftBlock.java:171)
	at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlock.setType(CraftBlock.java:165)
	at DynaTech 1.0.0.jar//me.profelements.dynatech.items.tools.Orechid.tick(Orechid.java:53)
	at DynaTech 1.0.0.jar//me.profelements.dynatech.items.electric.abstracts.AMachine$3.tick(AMachine.java:171)
	at Slimefun4.jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickBlock(TickerTask.java:189)
	at Slimefun4.jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickLocation(TickerTask.java:176)
	at Slimefun4.jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickChunk(TickerTask.java:146)
	at Slimefun4.jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.run(TickerTask.java:115)
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by Seggan** [comment]
Reset back

**Comment by Seggan** [comment]
Or we can make the ticker sync...

**Comment by ProfElements** [comment]
Cant make it sync until I refactor AMachine into more parts. Slowly working through it.

**Pull request merged**
