### PR TITLE
Adding the Growth Chamber MK2

### PR DESCRIPTION
**Pull request by waleks647**
It's an improved version of the current growth chamber.
It yields 4x the amounts of the growth chamber while using only 2x as much power.
It has 9 input slots and 27 output slots.

As you see I made an entire new "AMachineMK2" file, the reason for that is because I wanted the new machine to have more input and output slots but didn't see another way to do it without making a new file and changing the registered slots. I also made the "GrowthChamberMK2" file because I also didn't see a way to change the amounts it produces without affecting the already existing machine. I haven't tested it yet to see that nothing breaks, so if you could take a quick peak at the code and tell me if you see anything that could easily break I'd thank that a lot.

### CODE REVIEW

**Comment by ProfElements** [comment]
Please use the [Antigravity Bubble](https://github.com/ProfElements/DynaTech/blob/master/src/main/java/me/profelements/dynatech/items/electric/AntigravityBubble.java) as a reference make a new ui instead of making a seperate abstract machine. 

AMachineMK2 is not needed at all. That is currently that I all see

**Comment by waleks647** [comment]
Got it

**Comment by ProfElements** [comment]
Why did you close it?

**Comment by ProfElements** [comment]
You an just add a commit

**Comment by waleks647** [comment]
I'm making the file, will reopen when done

**Comment by ProfElements** [comment]
oh ok 👍

**Pull request closed without merging**
