### PR TITLE
Adding the Growth Chamber MK2

### PR DESCRIPTION
**Pull request by waleks647**
It's an improved version of the current growth chamber.
It yields 4x the amounts of the growth chamber while using only 2x as much power.
It has 9 input slots and 27 output slots.
It's also a much nicer lime glass.

### CODE REVIEW

**Comment by ProfElements** [comment]
https://imgur.com/a/3ZMEpTx it currently doesnt even show the output slots.

**Comment by waleks647** [comment]
There's no panes after that output row, that might be the cause?

**Comment by ProfElements** [comment]
Probably, also iirc you can just extend the GrowthChamber original

**Comment by ProfElements** [comment]
I can push my updated version? It still doesnt show the output slots though

**Comment by waleks647** [comment]
I'll try adding a pane at the end, to see if it recognizes it

**Comment by waleks647** [comment]
God finally it passed the check

**Comment by ProfElements** [comment]
<https://imgur.com/a/YvrY7jh> this looks a little dumb currently please fix it up

**Comment by waleks647** [comment]
Wdym fix it?
removing the pane at bottom right, yes
but I wanted it to have a lot of output slots but I guess I'll make it have 7 input and 21 output
thanks for the word

**Comment by ProfElements** [comment]
<https://imgur.com/a/F19NGa4> If you want to this might be an idea for the ui

**Comment by waleks647** [comment]
yes that's what I was thinking to do

**Comment by waleks647** [comment]
Ok that last commit finally settled it and now the gcmk2 is working as intended without any errors in the console or any undesired effect
but I noticed that despite the increased amount of output slots it won't output more than one set of products at a time without it needing the slots to be empty; is there a way to make it so it doesn't need the output slots to be empty?

**Comment by ProfElements** [comment]
You would have to modify AMachine, I was looking at this the other day trying to find a way to get it working.

**Comment by waleks647** [comment]
Ah well it's okay if it's that way. Other than that as I said the machine looks good to me so if you'd be ok to merge it now or if there's anything with it tell me, thanks.

**Comment by ProfElements** [comment]
Im fixing it as we speak
Took at peak at Silmefun's container to see if I could do it that way

**Comment by waleks647** [comment]
Oh well thanks for that!

**Comment by ProfElements** [comment]
:eyes: I dont think 1 carrot to 12 will make very many people on server happy

**Comment by waleks647** [comment]
Hm I was doing that for the 4x products, and saw that carrots give 3 so math is 12

**Comment by waleks647** [comment]
I suppose a better way of balancing it is to make the recipe need two growth chambers and put the 12 to a 8

**Comment by ProfElements** [comment]
Thank you for the pull request 👍  Just merged.

**Comment by waleks647** [comment]
Oh good, no need to balance it now

**Pull request merged**
