### PR TITLE
Adding the "Hydro/Water Turbine"

### PR DESCRIPTION
**Pull request by waleks647**
It's an upgraded version of the hydro generator, for a bit more space efficiency.
I don't know much about coding so I made it by following what was already in base by the hydro generator, just duplicating it and changing some values.

### CODE REVIEW

**Comment by ProfElements** [comment]
One things from what I see. I dont think HydroTurbine.java is needed at all. you can use a new instantiation of HydroGenerator instead, and it should work just the same

**Comment by waleks647** [comment]
> you can use a new instantiation of HydroGenerator instead

I don't know how to do that, so you're free to pick which way you'd want it to be, I'm just fine with having the new hydro turbine.

**Comment by ProfElements** [comment]
thank you for the pull request! Merged.

**Comment by waleks647** [comment]
Thank you too!

**Pull request merged**
